"""
Stock universe definitions for Indian market scanner.
All tickers are NSE symbols (suffix .NS added at fetch time).
"""

# ── NIFTY 50 ────────────────────────────────────────────────────────────────
NIFTY_50 = [
    "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO",
    "BAJFINANCE", "BAJAJFINSV", "BPCL", "BHARTIARTL", "BRITANNIA",
    "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "GRASIM",
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO",
    "HINDUNILVR", "ICICIBANK", "INDUSINDBK", "INFY", "ITC",
    "JSWSTEEL", "KOTAKBANK", "LTTS", "LT", "M&M",
    "MARUTI", "NESTLEIND", "NTPC", "ONGC", "POWERGRID",
    "RELIANCE", "SBICARD", "SBILIFE", "SUNPHARMA", "TATACONSUM",
    "TATAPOWER", "TATASTEEL", "TECHM", "TITAN", "TRENT",
    "ULTRACEMCO", "WIPRO", "HDFCAMC", "DIVISLAB", "SHRIRAMFIN"
]

# ── BANK NIFTY ──────────────────────────────────────────────────────────────
BANK_NIFTY = [
    "AUBANK", "AXISBANK", "BANDHANBNK", "FEDERALBNK", "HDFCBANK",
    "ICICIBANK", "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK", "PNB",
    "SBIN", "BANKBARODA", "BANKINDIA", "CANBK", "CENTRALBK",
    "IOB", "MAHABANK", "UNIONBANK", "UCOBANK", "INDIANB"
]

# ── NIFTY NEXT 50 ──────────────────────────────────────────────────────────
NIFTY_NEXT_50 = [
    "ABB", "ACC", "ADANIENT", "ADANIGREEN", "AMBUJACEM",
    "ASHOKLEY", "ASTRAL", "ATUL", "AVALONLABS", "BALKRISIND",
    "BIOCON", "BOSCHLTD", "CANFINHOME", "CHAMBLFERT", "COFORGE",
    "CONCOR", "COROMANDEL", "CROMPTON", "CUMMINSIND", "DALBHARAT",
    "DEEPAKNTR", "DIXON", "EMAMILTD", "ESCORTS", "GLENMARK",
    "GODREJCP", "GODREJPROP", "GSPL", "HAL", "HONAUT",
    "IDEA", "INDHOTEL", "IRCTC", "JUBLFOOD", "KPITTECH",
    "LALPATHLAB", "LICHSGFIN", "LUPIN", "MANAPPURAM", "MARICO",
    "MFSL", "MGL", "MOTHERSON", "MPHASIS", "MUTHOOTFIN",
    "NAM-INDIA", "OBEROIRLTY", "PERSISTENT", "PETRONET", "PFIZER"
]

# ── NIFTY MIDCAP 100 ──────────────────────────────────────────────────────
NIFTY_MIDCAP_100 = [
    "ABCAPITAL", "ABFRL", "ALKEM", "ASHOKLEY", "ASTRAL",
    "BALKRISIND", "BATAINDIA", "BEL", "BIOCON", "BOSCHLTD",
    "CANFINHOME", "CHAMBLFERT", "COFORGE", "CONCOR", "COROMANDEL",
    "CROMPTON", "CUMMINSIND", "DALBHARAT", "DEEPAKNTR", "DIXON",
    "EMAMILTD", "ESCORTS", "GLENMARK", "GODREJCP", "GODREJPROP",
    "GSPL", "HAL", "HONAUT", "INDHOTEL", "IRCTC",
    "JUBLFOOD", "KPITTECH", "LALPATHLAB", "LICHSGFIN", "LUPIN",
    "MANAPPURAM", "MARICO", "MFSL", "MGL", "MOTHERSON",
    "MPHASIS", "MUTHOOTFIN", "OBEROIRLTY", "PERSISTENT", "PETRONET",
    "PIIND", "PRESTIGE", "PVRINOX", "RAJESHEXPO", "RAMCOCEM",
    "RBLBANK", "RECLTD", "SAIL", "SOLARINDS", "SONACOMS",
    "SUNDARMFIN", "SUPREMEIND", "TATACHEM", "TORNTPHARM", "TATAPOWER",
    "VOLTAS", "ZEEL", "ZYDUSLIFE", "FEDERALBNK", "IDFCFIRSTB",
    "INDIACEM", "INDUSTOWER", "JSL", "NATIONALUM", "NMDC",
    "OFSS", "PNCINFRA", "POLYCAB", "TATACOMM",
    "TATAMETALI", "THERMAX", "TITAN", "TRENT", "TVSMOTOR",
    "UBL", "UNIONBANK", "VSTIND", "WHIRLPOOL", "ZENSARTECH"
]

# ── NIFTY SMALLCAP 100 ─────────────────────────────────────────────────────
NIFTY_SMALLCAP_100 = [
    "AFFLE", "ALKYLAMINE", "ANGELONE", "APTUS", "ASTER",
    "BIRLASOFT", "BLUESTARCO", "BSOFT", "CAMPUS", "CDSL",
    "CENTURYPLY", "CLEAN", "CAMS", "CYIENT", "DATAPATTNS",
    "EASEMYTRIP", "ELECON", "ELGIEQUIP", "GALAXYSURF",
    "GRINDWELL", "HAPPSTMNDS", "IIFL",
    "INDIAMART", "JYOTHYLAB", "KAJARIACER",
    "KPITTECH", "KRBL", "LATENTVIEW", "LEMONTREE",
    "METROPOLIS", "MOTILALOFS", "NATCOPHARM",
    "NEWGEN", "PHOENIXLTD", "PIIND",
    "PRINCEPIPE", "RATNAMANI", "RELAXO", "RITES",
    "SANOFI", "SCHAEFFLER", "SOBHA",
    "SONATSOFTW", "SRF", "SUDARSCHEM",
    "SUPRAJIT", "TATVA", "TRIDENT",
    "UTIAMC", "VAIBHAVGBL", "WELCORP", "WELSPUNIND",
    "WESTLIFE", "WPIL", "ZFCVINDIA", "ZYDUSWELL"
]

# ── FnO STOCKS (Futures & Options enabled) ──────────────────────────────────
FNO_STOCKS = [
    # Nifty components + high liquidity F&O stocks
    "ADANIPORTS", "ADANIENT", "ADANIGREEN", "AMBUJACEM", "APOLLOHOSP",
    "ASHOKLEY", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE",
    "BAJAJFINSV", "BALRAMCHIN", "BALKRISIND", "BANDHANBNK", "BHEL",
    "BPCL", "BRITANNIA", "CANBK", "CHAMBLFERT", "CIPLA",
    "COALINDIA", "COLPAL", "CONCOR", "COROMANDEL", "CROMPTON",
    "CUMMINSIND", "DALBHARAT", "DEEPAKNTR", "DIVISLAB", "DIXON",
    "EICHERMOT", "ESCORTS", "FEDERALBNK", "GAIL", "GLENMARK",
    "GODREJCP", "GODREJPROP", "GRASIM", "GSPL", "HAL",
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO",
    "HINDCOPPER", "HINDUNILVR", "ICICIBANK", "IDEA", "INDIACEM",
    "INDUSINDBK", "INFY", "IOC", "IRCTC", "ITC",
    "JINDALSTEL", "JSWENERGY", "JSWSTEEL", "KOTAKBANK", "LICHSGFIN",
    "LT", "LUPIN", "M&M", "MANAPPURAM", "MARICO",
    "MARUTI", "MFSL", "MGL", "MOTHERSON", "MPHASIS",
    "MUTHOOTFIN", "NATIONALUM", "NTPC", "ONGC", "PERSISTENT",
    "PETRONET", "PFC", "PIDILITIND", "PNB", "POLYCAB",
    "POWERGRID", "PVRINOX", "RECLTD", "RELIANCE", "SAIL",
    "SBICARD", "SBILIFE", "SBIN", "SHRIRAMFIN", "SONACOMS",
    "SRF", "SUNPHARMA", "TATACHEM", "TATACOMM", "TATACONSUM",
    "TATAELXSI", "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TCS",
    "TECHM", "TORNTPHARM", "TRENT", "TVSMOTOR", "UBL",
    "ULTRACEMCO", "VEDL", "VOLTAS", "WIPRO", "ZEEL"
]

# ── CASH MARKET (High liquidity NSE stocks) ────────────────────────────────
CASH_MARKET = list(set(
    NIFTY_50 + BANK_NIFTY + NIFTY_NEXT_50 + FNO_STOCKS
))

# ── BSE SENSEX 30 ──────────────────────────────────────────────────────────
BSE_SENSEX = [
    "AXISBANK", "ASIANPAINT", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV",
    "BPCL", "BHARTIARTL", "BRITANNIA", "CIPLA", "COALINDIA",
    "DRREDDY", "EICHERMOT", "HCLTECH", "HDFCBANK", "HDFCLIFE",
    "HEROMOTOCO", "HINDUNILVR", "ICICIBANK", "INFY", "ITC",
    "KOTAKBANK", "LT", "M&M", "MARUTI", "NESTLEIND",
    "NTPC", "ONGC", "POWERGRID", "RELIANCE", "SBIN",
    "SUNPHARMA", "TCS", "TATACONSUM", "TATASTEEL", "TECHM",
    "TITAN", "ULTRACEMCO", "WIPRO"
]

# ── BSE MIDCAP ──────────────────────────────────────────────────────────────
BSE_MIDCAP = [
    "ABCAPITAL", "ABFRL", "ALKEM", "ASHOKLEY", "ASTRAL",
    "BALKRISIND", "BEL", "BIOCON", "BOSCHLTD", "CANFINHOME",
    "COFORGE", "CONCOR", "CROMPTON", "CUMMINSIND", "DALBHARAT",
    "DEEPAKNTR", "DIXON", "ESCORTS", "GLENMARK", "GODREJCP",
    "GODREJPROP", "HAL", "HONAUT", "INDHOTEL", "IRCTC",
    "JUBLFOOD", "LALPATHLAB", "LUPIN", "MARICO", "MOTHERSON",
    "PERSISTENT", "PETRONET", "PIIND", "PRESTIGE", "RAMCOCEM",
    "RECLTD", "SOLARINDS", "TATACHEM", "TORNTPHARM", "TATAPOWER",
    "VOLTAS", "ZEEL", "ZYDUSLIFE", "TVSMOTOR", "UBL"
]

# ── BSE SMALLCAP ────────────────────────────────────────────────────────────
BSE_SMALLCAP = [
    "AFFLE", "ANGELONE", "APTUS", "ASTER", "BIRLASOFT",
    "BLUESTARCO", "BSOFT", "CDSL", "CYIENT", "DATAPATTNS",
    "ELECON", "ELGIEQUIP", "GRINDWELL", "HAPPSTMNDS", "INDIAMART",
    "KPITTECH", "KRBL", "LATENTVIEW", "LEMONTREE", "METROPOLIS",
    "MOTILALOFS", "NATCOPHARM", "NEWGEN", "PHOENIXLTD",
    "PRINCEPIPE", "RATNAMANI", "RELAXO", "RITES", "SANOFI",
    "SCHAEFFLER", "SOBHA", "SONATSOFTW", "SRF", "TATVA",
    "UTIAMC", "VAIBHAVGBL", "WELCORP", "WELSPUNIND"
]

# ── NIFTY IT ────────────────────────────────────────────────────────────────
NIFTY_IT = [
    "COFORGE", "HCLTECH", "INFY", "LTTS", "MPHASIS",
    "PERSISTENT", "TCS", "TECHM", "WIPRO", "ZENSARTECH"
]

# ── NIFTY PHARMA ────────────────────────────────────────────────────────────
NIFTY_PHARMA = [
    "ALKEM", "AUROPHARMA", "BIOCON", "CIPLA", "DRREDDY",
    "GLENMARK", "LUPIN", "SUNPHARMA", "TORNTPHARM", "ZYDUSLIFE"
]

# ── NIFTY AUTO ──────────────────────────────────────────────────────────────
NIFTY_AUTO = [
    "ASHOKLEY", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO", "M&M",
    "MARUTI", "MOTHERSON", "TATAPOWER", "TVSMOTOR", "BHARATFORG"
]

# ── NIFTY METAL ────────────────────────────────────────────────────────────
NIFTY_METAL = [
    "HINDALCO", "JSWSTEEL", "NATIONALUM", "NMDC", "SAIL",
    "TATASTEEL", "VEDL", "WELCORP", "COALINDIA"
]

# ── NIFTY REALTY ────────────────────────────────────────────────────────────
NIFTY_REALTY = [
    "BRIGADE", "DLF", "GODREJPROP", "OBEROIRLTY", "PHOENIXLTD",
    "PRESTIGE", "SOBHA", "LODHA"
]

# ── NIFTY ENERGY ────────────────────────────────────────────────────────────
NIFTY_ENERGY = [
    "BPCL", "GAIL", "HINDPETRO", "IOC", "NTPC",
    "ONGC", "POWERGRID", "RELIANCE", "TATAPOWER"
]

# ── NIFTY FINANCIAL SERVICES ────────────────────────────────────────────────
NIFTY_FINANCIAL = [
    "BAJFINANCE", "BAJAJFINSV", "HDFCBANK", "HDFCLIFE", "ICICIBANK",
    "ICICIPRULI", "KOTAKBANK", "LICHSGFIN", "SBICARD", "SBILIFE",
    "SBIN", "SHRIRAMFIN"
]

# ── BROADER MARKET ─────────────────────────────────────────────────────────
NIFTY_BROAD = list(set(
    NIFTY_50 + BANK_NIFTY + NIFTY_NEXT_50 + NIFTY_MIDCAP_100 + NIFTY_SMALLCAP_100
))

# ── Universe Map ────────────────────────────────────────────────────────────
UNIVERSES = {
    # NSE Indexes
    "NIFTY 50":           NIFTY_50,
    "BANK NIFTY":         BANK_NIFTY,
    "NIFTY NEXT 50":      NIFTY_NEXT_50,
    "NIFTY MIDCAP 100":   NIFTY_MIDCAP_100,
    "NIFTY SMALLCAP 100": NIFTY_SMALLCAP_100,

    # Market Segment
    "FnO STOCKS":         FNO_STOCKS,
    "CASH MARKET":        CASH_MARKET,

    # BSE Indexes
    "BSE SENSEX":         BSE_SENSEX,
    "BSE MIDCAP":         BSE_MIDCAP,
    "BSE SMALLCAP":       BSE_SMALLCAP,

    # Sector Indexes
    "NIFTY IT":           NIFTY_IT,
    "NIFTY PHARMA":       NIFTY_PHARMA,
    "NIFTY AUTO":         NIFTY_AUTO,
    "NIFTY METAL":        NIFTY_METAL,
    "NIFTY REALTY":       NIFTY_REALTY,
    "NIFTY ENERGY":       NIFTY_ENERGY,
    "NIFTY FINANCIAL":    NIFTY_FINANCIAL,

    # Combined
    "ALL (Combined)":     NIFTY_BROAD,
}
