"""
Stock universe definitions for Indian market scanner.
All tickers are NSE symbols (suffix .NS added at fetch time).
"""

# ── NIFTY 50 ────────────────────────────────────────────────────────────────
NIFTY_50 = [
    "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO",
    "BAJFINANCE", "BAJAJFINSV", "BPCL", "BHARTIARTL", "BRITANNIA",
    "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "GRASIM",
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO",
    "HINDUNILVR", "ICICIBANK", "INDUSINDBK", "INFY", "ITC",
    "JSWSTEEL", "KOTAKBANK", "LTTS", "LT", "M&M",
    "MARUTI", "NESTLEIND", "NTPC", "ONGC", "POWERGRID",
    "RELIANCE", "SBICARD", "SBILIFE", "SUNPHARMA",    "TATACONSUM",
    "TATAPOWER", "TATASTEEL", "TECHM", "TITAN", "TRENT",
    "ULTRACEMCO", "WIPRO", "HDFCAMC", "DIVISLAB", "SHRIRAMFIN"
]

# ── BANK NIFTY ──────────────────────────────────────────────────────────────
BANK_NIFTY = [
    "AUBANK", "AXISBANK", "BANDHANBNK", "FEDERALBNK", "HDFCBANK",
    "ICICIBANK", "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK", "PNB",
    "SBIN", "BANKBARODA", "BANKINDIA", "CANBK", "CENTRALBK",
    "IOB", "MAHABANK", "UNIONBANK", "UCO BANK", "INDIANB"
]

# ── NIFTY NEXT 50 ──────────────────────────────────────────────────────────
NIFTY_NEXT_50 = [
    "ABB", "ACC", "ADANIENT", "ADANIGREEN", "AMBUJACEM",
    "ASHOKLEY", "ASTRAL", "ATUL", "AVALONLABS", "BALKRISIND",
    "BIOCON", "BOSCHLTD", "CANFINHOME", "CHAMBLFERT", "COFORGE",
    "CONCOR", "COROMANDEL", "CROMPTON", "CUMMINSIND", "DALBHARAT",
    "DEEPAKNTR", "DIXON", "EMAMILTD", "ESCORTS", "GLENMARK",
    "GODREJCP", "GODREJPROP", "GSPL", "HAL", "HONAUT",
    "IDEA", "INDHOTEL", "IRCTC", "JUBLFOOD", "KPITTECH",
    "LALPATHLAB", "LICHSGFIN", "LUPIN", "MANAPPURAM", "MARICO",
    "MFSL", "MGL", "MOTHERSON", "MPHASIS", "MUTHOOTFIN",
    "NAM-INDIA", "OBEROIRLTY", "PERSISTENT", "PETRONET", "PFIZER"
]

# ── NIFTY MIDCAP 100 (partial representative set) ──────────────────────────
NIFTY_MIDCAP_100 = [
    "ABCAPITAL", "ABFRL", "ALKEM", "ASHOKLEY", "ASTRAL",
    "BALKRISIND", "BATAINDIA", "BEL", "BIOCON", "BOSCHLTD",
    "CANFINHOME", "CHAMBLFERT", "COFORGE", "CONCOR", "COROMANDEL",
    "CROMPTON", "CUMMINSIND", "DALBHARAT", "DEEPAKNTR", "DIXON",
    "EMAMILTD", "ESCORTS", "GLENMARK", "GODREJCP", "GODREJPROP",
    "GSPL", "HAL", "HONAUT", "INDHOTEL", "IRCTC",
    "JUBLFOOD", "KPITTECH", "LALPATHLAB", "LICHSGFIN", "LUPIN",
    "MANAPPURAM", "MARICO", "MFSL", "MGL", "MOTHERSON",
    "MPHASIS", "MUTHOOTFIN", "OBEROIRLTY", "PERSISTENT", "PETRONET",
    "PIIND", "PRESTIGE", "PVRINOX", "RAJESHEXPO", "RAMCOCEM",
    "RBLBANK", "RECLTD", "SAIL", "SOLARINDS", "SONACOMS",
    "SUNDARMFIN", "SUPREMEIND", "TATACHEM", "TORNTPHARM", "TATAPOWER",
    "VOLTAS", "ZEEL", "ZYDUSLIFE", "FEDERALBNK", "IDFCFIRSTB",
    "INDIACEM", "INDUSTOWER", "JSL", "NATIONALUM", "NMDC",
    "OBEROIRLTY", "OFSS", "PNCINFRA", "POLYCAB", "RAJESHEXPO",
    "SAPPHIRE", "SOUTHBANK", "STARHEALTH", "SUNDRMFAST", "TATACOMM",
    "TATAMETALI", "THERMAX", "TITAN", "TRENT", "TVSMOTOR",
    "UBL", "UNIONBANK", "VSTIND", "WHIRLPOOL", "ZENSARTECH"
]

# ── NIFTY SMALLCAP 100 (partial representative set) ─────────────────────────
NIFTY_SMALLCAP_100 = [
    "AARTI", "AAVAS", "AFFLE", "ALKYLAMINE", "ANGELONE",
    "APTUS", "ASTER", "BASF", "BAYANDBREW", "BIRLASOFT",
    "BLUESTARCO", "BSOFT", "CAMPUS", "CDSL", "CENTURYPLY",
    "CLEAN", "CAMS", "COMPUTECH", "CYIENT", "DATAPATTNS",
    "EASEMYTRIP", "ELECON", "ELGIEQUIP", "FINOLEX", "GALAXYSURF",
    "GARFIBRES", "GRINDWELL", "HAPPSTMNDS", "HGS", "IIFL",
    "INDIAMART", "INGERRAND", "IOB", "JYOTHYLAB", "KAJARIACER",
    "KANSAINER", "KESORAMIND", "KNRCON", "KPITTECH", "KRBL",
    "LATENTVIEW", "LEMONTREE", "MAHLOG", "MAHSEAMLES", "MANORAMA",
    "MAPMYINDIA", "METROPOLIS", "MOTILALOFS", "NATCOPHARM", "NAVNETEDUL",
    "NETWORK18", "NEWGEN", "PGHL", "PHOENIXLTD", "PIIND",
    "PRINCEPIPE", "PRIVISCL", "RATNAMANI", "RELAXO", "RITES",
    "Route", "SANOFI", "SAPPHIRE", "SCHAEFFLER", "SOBHA",
    "SONATSOFTW", "SPARC", "SRF", "STAR", "SUDARSCHEM",
    "SUNTV", "SUPRAJIT", "TATVA", "TINPLATE", "TRIDENT",
    "UTIAMC", "VAIBHAVGBL", "VSTIND", "WELCORP", "WELSPUNIND",
    "WESTLIFE", "WPIL", "ZFCVINDIA", "ZYDUSWELL", "ABCAPITAL"
]

# ── BROADER MARKET (All NSE - curated list of liquid mid/small caps) ────────
NIFTY_BROAD = list(set(
    NIFTY_50 + BANK_NIFTY + NIFTY_NEXT_50 + NIFTY_MIDCAP_100 + NIFTY_SMALLCAP_100
))

# ── SECTOR INDICES ──────────────────────────────────────────────────────────
NIFTY_IT = [
    "COFORGE", "HCLTECH", "INFY", "LTTS", "Mphasis",
    "PERSISTENT", "TCS", "TECHM", "WIPRO", "ZENSARTECH"
]

NIFTY_PHARMA = [
    "ALKEM", "AUROPHARMA", "BIOCON", "CIPLA", "DRREDDY",
    "GLENMARK", "IPCALAB", "LUPIN", "SUNPHARMA", "TORNTPHARM"
]

NIFTY_AUTO = [
    "ASHOKLEY", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO", "M&M",
    "MARUTI", "MOTHERSON", "TATAPOWER", "TVSMOTOR", "BHARATFORG"
]

NIFTY_METAL = [
    "HINDALCO", "JSWSTEEL", "NATIONALUM", "NMDC", "SAIL",
    "TATASTEEL", "VEDL", "WELCORP", "HINDZINC", "COALINDIA"
]

NIFTY_REALTY = [
    "BRIGADE", "DLF", "GODREJPROP", "OBEROIRLTY", "PHOENIXLTD",
    "PRESTIGE", "SOBHA", "STELHOUSING", "LODHA", "MAHLIFE"
]

# ── Universe Map ────────────────────────────────────────────────────────────
UNIVERSES = {
    "NIFTY 50":           NIFTY_50,
    "BANK NIFTY":         BANK_NIFTY,
    "NIFTY NEXT 50":      NIFTY_NEXT_50,
    "NIFTY MIDCAP 100":   NIFTY_MIDCAP_100,
    "NIFTY SMALLCAP 100": NIFTY_SMALLCAP_100,
    "NIFTY IT":           NIFTY_IT,
    "NIFTY PHARMA":       NIFTY_PHARMA,
    "NIFTY AUTO":         NIFTY_AUTO,
    "NIFTY METAL":        NIFTY_METAL,
    "NIFTY REALTY":       NIFTY_REALTY,
    "ALL (Combined)":     NIFTY_BROAD,
}
